name: 'Build and Release DEB Package'

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential libcurl4-openssl-dev
      
      - name: Extract version from git tag
        id: get_version
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "Building version: ${VERSION}"

      - name: Configure with version from tag
        run: cmake -B build -DPROJECT_VERSION="${{ steps.get_version.outputs.VERSION }}"
      
      - name: Build project
        run: cmake --build build
      
      - name: Create DEB package
        run: |
          cd build
          cpack -G DEB
      
      - name: List generated DEB files
        run: ls -la ./build/*.deb
      
      - name: Create Release
        uses: softprops/action-gh-release@v1 
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ./build/tree-utility.deb