name: 'Build and Release DEB Package'

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libcurl4-openssl-dev

    - name: Extract version from git tag
      id: get_version
      run: |
        VERSION="${GITHUB_REF#refs/tags/v}"
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        echo "Building version: ${VERSION}"

    - name: Configure with version from tag
      run: |
        cmake -B build -DPROJECT_VERSION="${{ steps.get_version.outputs.VERSION }}"

    - name: Build project
      run: |
        cmake --build build

    - name: Create DEB package
      run: |
        cd build
        cpack -G DEB
        ls -la *.deb

    - name: Upload to GitHub Releases
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        artifacts: "build/*.deb"
        token: ${{ secrets.GITHUB_TOKEN }}